### PR TITLE
Only restart vaani if an update happens

### PR DESCRIPTION
**Pull request by Cwiiis**

### CODE REVIEW

**Comment by Cwiiis** [comment]
This is untested, please verify it works before merging :)

**Comment by kdavis-mozilla** [comment]
Oh you did it in both repos. I'll test this.

**Comment by kdavis-mozilla** [comment]
Upon a cold start where the local `vaani.client` is older than the remote it works...

```
...
Aug 31 01:45:49 vaani git-auto-updater[766]: git-auto-updater starting with configuration:
Aug 31 01:45:49 vaani git-auto-updater[766]: repository: https://github.com/mozilla/vaani.client
Aug 31 01:45:49 vaani git-auto-updater[766]: branch: deployed
Aug 31 01:45:49 vaani git-auto-updater[766]: path: /opt/vaani.client
Aug 31 01:45:49 vaani git-auto-updater[766]: update time: 2:0
Aug 31 01:45:49 vaani git-auto-updater[766]: error retry frequency: 1 minutes
Aug 31 01:45:49 vaani git-auto-updater[766]: command: bash "/opt/vaani.raspberrypi/client/update.sh"
Aug 31 01:45:49 vaani git-auto-updater[766]: Already on 'deployed'
Aug 31 01:45:49 vaani git-auto-updater[766]: Checking for update...
Aug 31 01:45:51 vaani git-auto-updater[766]: Current revision: 16d7879b949737d921146e346d42a107dfc9b7f7
Aug 31 01:45:51 vaani git-auto-updater[766]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 01:45:51 vaani git-auto-updater[766]: Updating...
Aug 31 01:45:51 vaani git-auto-updater[766]: Updated.
Aug 31 01:45:51 vaani git-auto-updater[766]: start vaani [ '/opt/vaani.raspberrypi/client/update.sh', 1 ]
Aug 31 01:45:51 vaani git-auto-updater[766]: Scheduling update for 900 seconds from now
Aug 31 01:45:51 vaani systemd[1]: Starting Vaani Client...
Aug 31 01:45:51 vaani systemd[1]: Started Vaani Client.
Aug 31 01:45:52 vaani node[786]: config.json
...
```

**Comment by kdavis-mozilla** [comment]
However, the problem described in andrenatal/git-auto-updater issue 7[[1]](https://github.com/andrenatal/git-auto-updater/issues/7), multiple update attempts in the target minute, still happens...

```
...
Aug 31 02:00:51 vaani git-auto-updater[766]: Checking for update...
Aug 31 02:00:52 vaani git-auto-updater[766]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:52 vaani git-auto-updater[766]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:52 vaani git-auto-updater[766]: Scheduling update for 0 seconds from now
Aug 31 02:00:52 vaani git-auto-updater[766]: Checking for update...
Aug 31 02:00:53 vaani git-auto-updater[766]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:53 vaani git-auto-updater[766]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:53 vaani git-auto-updater[766]: Scheduling update for 0 seconds from now
Aug 31 02:00:54 vaani git-auto-updater[766]: Checking for update...
Aug 31 02:00:55 vaani git-auto-updater[766]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:55 vaani git-auto-updater[766]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:55 vaani git-auto-updater[766]: Scheduling update for 0 seconds from now
Aug 31 02:00:57 vaani git-auto-updater[766]: Checking for update...
Aug 31 02:00:58 vaani git-auto-updater[766]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:58 vaani git-auto-updater[766]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:58 vaani git-auto-updater[766]: Scheduling update for 0 seconds from now
Aug 31 02:00:59 vaani git-auto-updater[766]: Checking for update...
Aug 31 02:01:00 vaani node[786]: METRICS - event string:v=1&t=event&tid=UA-77033033-1&cid=b827eb9c1ee5&ec=heartbeat&ea=hb&el=ok&ev=1&an=vaani-test&av=0.1&ul=pt-br&cd1=osx&cd2=elcapitan&cd3=pc&cd4=x64&cd5=node&cd6=b827eb9c1ee5&cd7=2016-08-30 20:01:00
Aug 31 02:01:00 vaani rsyslogd-2007: action 'action 17' suspended, next retry is Wed Aug 31 02:02:00 2016 [try http://www.rsyslog.com/e/2007 ]
Aug 31 02:01:00 vaani node[786]: METRICS - Sending request...
Aug 31 02:01:00 vaani node[786]: METRICS - request returned: 200
Aug 31 02:01:00 vaani node[786]: METRICS - event recorded: heartbeat, hb, ok, 1
Aug 31 02:01:00 vaani git-auto-updater[766]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:01:00 vaani git-auto-updater[766]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:01:00 vaani git-auto-updater[766]: Scheduling update for 86340 seconds from now
...
```

Yes, I know this pull request is not meant to fix andrenatal/git-auto-updater issue 7[[1]](https://github.com/andrenatal/git-auto-updater/issues/7).

**Comment by kdavis-mozilla** [comment]
I still need to check that if an update is needed while the git-auto-updater is running, not before it starts, that the update occurs without a problem.

**Comment by Cwiiis** [comment]
Part of the problem still happens, but it has less consequence now - I'll fix git-auto-updater tomorrow but if this was time sensitive, I think we could ship with it.

**Comment by kdavis-mozilla** [comment]
It needs to ship tomorrow, and I still need to test the case described in the previous comment[[1]](https://github.com/mozilla/vaani.raspberrypi/pull/10#issuecomment-243566624).

**Comment by Cwiiis** [comment]
Fwiw, I don't see why this commit would have any effect on that, but it's always best to check. Like I said, I'll fix the git-auto-updater problem tomorrow (morning), but assuming that those repeated git pulls don't cause any problems (could we end up rate-limited by GitHub?), we could ship like this. If you aren't confident in this change, we could ship without it too.

**Comment by kdavis-mozilla** [comment]
I am going to run the test case described in the previous comment[[1]](https://github.com/mozilla/vaani.raspberrypi/pull/10#issuecomment-243566624) tomorrow morning and if it works I'll make an image.

I'm **_not_** going to include whatever you do tomorrow morning as I think we can live with the "repeated git pulls" and I don't have time to re-test everything again with the changes you make tomorrow morning.

**Comment by Cwiiis** [comment]
Sounds good - I'll still fix it though :)

**Comment by kdavis-mozilla** [comment]
Ok the final test seems like it worked

```
...
Aug 31 01:39:39 vaani git-auto-updater[767]: start vaani [ '/opt/vaani.raspberrypi/client/update.sh', 1 ]
Aug 31 01:39:39 vaani git-auto-updater[767]: Scheduling update for 1260 seconds from now
...
Aug 31 02:00:41 vaani git-auto-updater[767]: Current revision: 16d7879b949737d921146e346d42a107dfc9b7f7
Aug 31 02:00:41 vaani git-auto-updater[767]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:41 vaani git-auto-updater[767]: Updating...
Aug 31 02:00:41 vaani systemd[1]: Stopping Vaani Client...
Aug 31 02:00:41 vaani systemd[1]: Stopped Vaani Client.
Aug 31 02:00:41 vaani git-auto-updater[767]: Updated.
Aug 31 02:00:41 vaani git-auto-updater[767]: start vaani [ '/opt/vaani.raspberrypi/client/update.sh', 2 ]
Aug 31 02:00:41 vaani git-auto-updater[767]: Scheduling update for 0 seconds from now
Aug 31 02:00:41 vaani git-auto-updater[767]: Checking for update...
Aug 31 02:00:41 vaani systemd[1]: Starting Vaani Client...
Aug 31 02:00:41 vaani systemd[1]: Started Vaani Client.
...
Aug 31 02:00:44 vaani git-auto-updater[767]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:44 vaani git-auto-updater[767]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:44 vaani git-auto-updater[767]: Scheduling update for 0 seconds from now
Aug 31 02:00:44 vaani node[2327]: METRICS - request returned: 200
Aug 31 02:00:44 vaani node[2327]: METRICS - event recorded: boot, sucessfull, ok, 1
Aug 31 02:00:48 vaani git-auto-updater[767]: Checking for update...
Aug 31 02:00:49 vaani git-auto-updater[767]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:49 vaani git-auto-updater[767]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:49 vaani git-auto-updater[767]: Scheduling update for 0 seconds from now
Aug 31 02:00:50 vaani git-auto-updater[767]: Checking for update...
Aug 31 02:00:51 vaani git-auto-updater[767]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:51 vaani git-auto-updater[767]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:51 vaani git-auto-updater[767]: Scheduling update for 0 seconds from now
Aug 31 02:00:52 vaani git-auto-updater[767]: Checking for update...
Aug 31 02:00:53 vaani git-auto-updater[767]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:53 vaani git-auto-updater[767]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:53 vaani git-auto-updater[767]: Scheduling update for 0 seconds from now
Aug 31 02:00:54 vaani git-auto-updater[767]: Checking for update...
Aug 31 02:00:55 vaani git-auto-updater[767]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:55 vaani git-auto-updater[767]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:55 vaani git-auto-updater[767]: Scheduling update for 0 seconds from now
Aug 31 02:00:56 vaani git-auto-updater[767]: Checking for update...
Aug 31 02:00:56 vaani git-auto-updater[767]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:56 vaani git-auto-updater[767]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:56 vaani git-auto-updater[767]: Scheduling update for 0 seconds from now
Aug 31 02:00:57 vaani git-auto-updater[767]: Checking for update...
Aug 31 02:00:58 vaani git-auto-updater[767]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:58 vaani git-auto-updater[767]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:00:58 vaani git-auto-updater[767]: Scheduling update for 0 seconds from now
Aug 31 02:00:59 vaani git-auto-updater[767]: Checking for update...
Aug 31 02:01:00 vaani node[2327]: METRICS - event string:v=1&t=event&tid=UA-77033033-1&cid=b827eb9c1ee5&ec=heartbeat&ea=hb&el=ok&ev=1&an=vaani-test&av=0.1&ul=pt-br&cd1=osx&cd2=elcapitan&cd3=pc&cd4=x64&cd5=node&cd6=b827eb9c1ee5&cd7=2016-08-31 08:01:00
Aug 31 02:01:00 vaani node[2327]: METRICS - Sending request...
Aug 31 02:01:00 vaani node[2327]: METRICS - request returned: 200
Aug 31 02:01:00 vaani node[2327]: METRICS - event recorded: heartbeat, hb, ok, 1
Aug 31 02:01:00 vaani git-auto-updater[767]: Current revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:01:00 vaani git-auto-updater[767]: Latest revision: 1b669dd390bafde87f37c98be3e032d8458d5266
Aug 31 02:01:00 vaani git-auto-updater[767]: Scheduling update for 86340 seconds from now
...
```

So I' going to merge and create an image.

**Pull request merged**
